---
title: "Fig1_clean"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
	library(data.table)
	library(foreach)
	library(ggplot2)
	library(ggmap)
	library(maps)
	library(mapdata)
	library(cowplot)
  library(RColorBrewer)
```



## Figure 1A
```{r}
	locs <- fread("all_popinfo_formap_set.csv")
	
	locs[,dateApprox := !is.na(col_date)]
	locs[is.na(col_date), col_date:=paste(month, "15", gsub("20", "", year), sep="/")]
	locs[name=="melPA_72011_SPT", set:="Core20"]

	locs[,jDay := as.POSIXlt(col_date, format = "%m/%d/%y")$yday]
	locs[,lat := as.numeric(as.character(tstrsplit(latitude, "\\ ")[[1]]))]

	locs[set=="Cline" & pop_name=="PA_9" ,jDay:=jDay+1]
	locs[name=="melPA_112011_WIN_FRT", set:="extra"]
	
	locs[,season:=factor(season, levels=c("spring", "fall"))]



	### version 2
		### left panel
		latJday_spring <- 
			  ggplot(data=locs[set=="Core20"][order(jDay)][season=="spring"], aes(x=jDay, y=lat, fill=season)) + 
					scale_x_reverse() +
					facet_grid(.~season) + coord_flip() + coord_flip() + theme(legend.position="none") +
					geom_vline(xintercept=as.POSIXlt("6/20/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
					geom_vline(xintercept=as.POSIXlt("9/22/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
					geom_vline(xintercept=as.POSIXlt("12/21/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) +
					geom_segment(data=locs[set=="Core20"][order(jDay)][season=="spring"], aes(x=jDay, y=lat, xend=jDay, yend=50), color="grey", lwd=.5) +					
					geom_point(size=4, color="black", pch=21) + 
					xlim(385, 100) +
					ylim(30, 50) + 
			theme(legend.direction="vertical", 
			      legend.justification=c("right"), 
			      #      legend.position=c(1.1,0.5), 
			      legend.key.size = unit(0.35, "cm"),
			      legend.background=element_rect(fill="white", colour="white", linetype="solid", size=.25),
			      legend.text=element_text(size=6),
			      legend.title=element_text(size=8),
			      legend.title.align=0,
			      legend.margin=margin(0,0,0,0),
			      #      legend.box.just = "left",
			      axis.text=element_text(size=8),
			      axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 10)),
			      axis.title=element_text(size=10))  
			
		### middle panel
			locs.ag <- locs[set=="Core20"][order(jDay)][,list(jDay.mu=mean(jDay, na.rm=T),
															  jDay.spring=na.omit(jDay[season=="spring"]),
															  jDay.fall=jDay[season=="fall"],
															  lat=mean(lat),
															  dum="dum"), 
														list(pop_name)]
			locs.ag <- locs.ag[order(jDay.spring)]
			locs.ag$pop_name_new = c("CA_es_13" ,  "CA_tu_13" ,  "UA_od_13",  "WI_cp_12",   "CA_es_12" ,  "GA_at_14", "PA_sc_14", "KA_to_14",  "VA_ch_14",  "WI_cp_14",  "VA_ch_15",  "ES_ba_12",   "PA_li_10",   "PA_li_11", "MA_la_14",  "NY_it_12", "MI_bh_14",  "MA_la_12",   "ON_su_15",  "AT_gr_12")
											
			compression.scale <- -.2											
			locs.ag[,jDay.spaced := seq(from=min(jDay.spring)*(1+compression.scale), to=max(jDay.fall)*(1-compression.scale), length.out=length(jDay.mu))]
		
		  paired.plot <- 
			  ggplot() + scale_x_reverse() + coord_flip() + coord_flip() +
							geom_segment(data=locs.ag, aes(y=.5, x=jDay.spring, yend=.8, xend=jDay.spaced), color="grey", lwd=.5) +		
							geom_segment(data=locs.ag, aes(y=1.2, x=jDay.spaced, yend=1.5, xend=jDay.fall), color="grey", lwd=.5) +
							geom_segment(data=locs.ag, aes(y=.8, x=jDay.spaced, yend=1.2, xend=jDay.spaced), color="grey", lwd=.5) +
							geom_label(data=locs.ag, aes(y=1, x=jDay.spaced, label=pop_name_new), fill="white") +
							#facet_grid(~dum) + xlim(365, 100) + 
			        facet_grid(~dum)  + xlim(385, 100) + 
							# theme(axis.title.y=element_blank(),
							# 	axis.text.y=element_blank(),
							# 	 axis.ticks.y=element_blank(),
							# 	 axis.line.y=element_blank())
			theme(legend.direction="vertical", 
			      legend.justification=c("right"), 
			      #      legend.position=c(1.1,0.5), 
			      legend.key.size = unit(0.35, "cm"),
			      legend.background=element_rect(fill="white", colour="white", linetype="solid", size=.25),
			      legend.text=element_text(size=6),
			      legend.title=element_text(size=8),
			      legend.title.align=0,
			      legend.margin=margin(0,0,0,0),
			      #      legend.box.just = "left",
			      axis.text=element_text(size=8),
			      axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 10)),
			      axis.title=element_text(size=10)) 
		

		### right panel
			latJday_fall <- 
			  ggplot(data=locs[set=="Core20"][order(jDay)][season=="fall"], aes(x=jDay, y=lat, fill=season)) + 
					scale_x_reverse() +
					facet_grid(.~season) + coord_flip() + coord_flip() + theme(legend.position="none") +
					geom_vline(xintercept=as.POSIXlt("6/20/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
					geom_vline(xintercept=as.POSIXlt("9/22/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
					geom_vline(xintercept=as.POSIXlt("12/21/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) +
					geom_segment(data=locs[set=="Core20"][order(jDay)][season=="fall"], aes(x=jDay, y=lat, xend=jDay, yend=33), color="grey", lwd=.5) +										
					geom_point(size=4, fill="#56B4E9", color="black", pch=21) + 
					xlim(385, 100) + ylim(30, 50) + 
			  theme(legend.direction="vertical", 
			        legend.justification=c("right"), 
			        #      legend.position=c(1.1,0.5), 
			        legend.key.size = unit(0.35, "cm"),
			        legend.background=element_rect(fill="white", colour="white", linetype="solid", size=.25),
			        legend.text=element_text(size=6),
			        legend.title=element_text(size=8),
			        legend.title.align=0,
			        legend.margin=margin(0,0,0,0),
			        #      legend.box.just = "left",
			        axis.text=element_text(size=8),
			        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 10)),
			        axis.title=element_text(size=10)) 
			    
			
			
		### joint plot	
			mp <- plot_grid(latJday_spring, paired.plot, latJday_fall, nrow=1, rel_widths=c(0.5, .75, 0.5))
			#ggsave(mp, file="map_vertical_May2018.pdf")
			#save_plot(mp, file="map_vertical2_May2018.pdf", base_aspect_ratio = 0.75, base_height=7)
	



####### Version Small
			### left panel
			latJday_spring <- 
			  ggplot(data=locs[set=="Core20"][order(jDay)][season=="spring"], aes(x=jDay, y=lat, fill=season)) + 
			  scale_x_reverse() +
			  facet_grid(.~season) + coord_flip() + coord_flip() + theme(legend.position="none") +
			  geom_vline(xintercept=as.POSIXlt("6/20/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
			  geom_vline(xintercept=as.POSIXlt("9/22/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
			  geom_vline(xintercept=as.POSIXlt("12/21/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) +
			  geom_segment(data=locs[set=="Core20"][order(jDay)][season=="spring"], aes(x=jDay, y=lat, xend=jDay, yend=50), color="grey", lwd=.5) +					
			  geom_point(size=4, color="black", pch=21) + 
			  xlim(385, 100) +
			  ylim(30, 50) + 
			  theme(legend.direction="vertical", 
			        legend.justification=c("right"), 
			        #      legend.position=c(1.1,0.5), 
			        legend.key.size = unit(0.35, "cm"),
			        legend.background=element_rect(fill="white", colour="white", linetype="solid", size=.25),
			        legend.text=element_text(size=6),
			        legend.title=element_text(size=8),
			        legend.title.align=0,
			        legend.margin=margin(0,0,0,0),
			        #      legend.box.just = "left",
			        axis.text=element_text(size=8),
			        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 10)),
			        axis.title=element_text(size=10))  
			
			### middle panel
			locs.ag <- locs[set=="Core20"][order(jDay)][,list(jDay.mu=mean(jDay, na.rm=T),
			                                                  jDay.spring=na.omit(jDay[season=="spring"]),
			                                                  jDay.fall=jDay[season=="fall"],
			                                                  lat=mean(lat),
			                                                  dum="dum"), 
			                                            list(pop_name)]
			locs.ag <- locs.ag[order(jDay.spring)]
			locs.ag$pop_name_new = c("CA_es_13" ,  "CA_tu_13" ,  "UA_od_13",  "WI_cp_12",   "CA_es_12" ,  "GA_at_14", "PA_sc_14", "KA_to_14",  "VA_ch_14",  "WI_cp_14",  "VA_ch_15",  "ES_ba_12",   "PA_li_10",   "PA_li_11", "MA_la_14",  "NY_it_12", "MI_bh_14",  "MA_la_12",   "ON_su_15",  "AT_gr_12")
			
			compression.scale <- -.2											
			locs.ag[,jDay.spaced := seq(from=min(jDay.spring)*(1+compression.scale), to=max(jDay.fall)*(1-compression.scale), length.out=length(jDay.mu))]
			
			paired.plot <- 
			  ggplot() + scale_x_reverse() + coord_flip() + coord_flip() +
			  geom_segment(data=locs.ag, aes(y=.5, x=jDay.spring, yend=.8, xend=jDay.spaced), color="grey", lwd=.5) +		
			  geom_segment(data=locs.ag, aes(y=1.2, x=jDay.spaced, yend=1.5, xend=jDay.fall), color="grey", lwd=.5) +
			  geom_segment(data=locs.ag, aes(y=.8, x=jDay.spaced, yend=1.2, xend=jDay.spaced), color="grey", lwd=.5) +
			  geom_label(data=locs.ag, aes(y=1, x=jDay.spaced, label=pop_name_new), fill="white") +
			  #facet_grid(~dum) + xlim(365, 100) + 
			  facet_grid(~dum)  + xlim(385, 100) + 
			  # theme(axis.title.y=element_blank(),
			  # 	axis.text.y=element_blank(),
			  # 	 axis.ticks.y=element_blank(),
			  # 	 axis.line.y=element_blank())
			  theme(legend.direction="vertical", 
			        legend.justification=c("right"), 
			        #      legend.position=c(1.1,0.5), 
			        legend.key.size = unit(0.35, "cm"),
			        legend.background=element_rect(fill="white", colour="white", linetype="solid", size=.25),
			        legend.text=element_text(size=6),
			        legend.title=element_text(size=8),
			        legend.title.align=0,
			        legend.margin=margin(0,0,0,0),
			        #      legend.box.just = "left",
			        axis.text=element_text(size=8),
			        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 10)),
			        axis.title=element_text(size=10)) 
			
			
			### right panel
			latJday_fall <- 
			  ggplot(data=locs[set=="Core20"][order(jDay)][season=="fall"], aes(x=jDay, y=lat, fill=season)) + 
			  scale_x_reverse() +
			  facet_grid(.~season) + coord_flip() + coord_flip() + theme(legend.position="none") +
			  geom_vline(xintercept=as.POSIXlt("6/20/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
			  geom_vline(xintercept=as.POSIXlt("9/22/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) + 
			  geom_vline(xintercept=as.POSIXlt("12/21/2010", format = "%m/%d/%y")$yday, lty="dashed", lwd=0) +
			  geom_segment(data=locs[set=="Core20"][order(jDay)][season=="fall"], aes(x=jDay, y=lat, xend=jDay, yend=33), color="grey", lwd=.5) +										
			  geom_point(size=4, fill="#56B4E9", color="black", pch=21) + 
			  xlim(385, 100) + ylim(30, 50) + 
			  theme(legend.direction="vertical", 
			        legend.justification=c("right"), 
			        #      legend.position=c(1.1,0.5), 
			        legend.key.size = unit(0.35, "cm"),
			        legend.background=element_rect(fill="white", colour="white", linetype="solid", size=.25),
			        legend.text=element_text(size=6),
			        legend.title=element_text(size=8),
			        legend.title.align=0,
			        legend.margin=margin(0,0,0,0),
			        #      legend.box.just = "left",
			        axis.text=element_text(size=8),
			        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 10)),
			        axis.title=element_text(size=10)) 
			
			
			
			### joint plot	
			plot_grid(latJday_spring+theme_cowplot(), paired.plot+theme_cowplot(), latJday_fall+theme_cowplot(), nrow=1, rel_widths=c(0.5, .75, 0.5))
			# mp <- plot_grid(latJday_spring, paired.plot, latJday_fall, nrow=1, rel_widths=c(0.5, .75, 0.5))
			#ggsave(mp, file="julianday_small_vertical_small_May2018.pdf")
			#save_plot(mp, file="julianday_small_vertical_small_May2018.pdf", base_aspect_ratio = 0.75, base_height=7)

## Finish figure in illustrator
```


# Figure 1B and figure S1: maps
```{r}
#################
### tidy map ###
#################

	### load data
		locs <- fread("popsTidy.csv")
		world <- as.data.table(map_data("world"))

	### make maps

		min.lat.eu <- 35
		max.lat.eu <- 55
		min.long.eu <- -10
		max.long.eu <- 37

		europe_tidy <- 	ggplot() + 
					geom_polygon(data = world[long>=min.long.eu & long<= max.long.eu][lat>=min.lat.eu & lat<=max.lat.eu], 
								aes(x=long, y = lat, group = group), fill="lightgrey") +
					geom_point(data = locs[longitude>=min.long.eu & longitude<= max.long.eu][latitude>=min.lat.eu & latitude<=max.lat.eu], 
								aes(x=longitude, y=latitude), size=5, color="green") + 
					geom_text(data = locs[longitude>=min.long.eu & longitude<= max.long.eu][latitude>=min.lat.eu & latitude<=max.lat.eu], 
								aes(x=longitude, y=latitude, label=nYears), size=3) + 		  				
					xlab("Longitude") + ylab("Latitude") 

		## north america
		min.lat.na <- 25
		max.lat.na <- 50
		min.long.na <- -130
		max.long.na <- -65

		northamerica_tidy <- ggplot() + 
					geom_polygon(data = world[long>=min.long.na & long<= max.long.na][lat>=min.lat.na & lat<=max.lat.na], 
								aes(x=long, y = lat, group = group), fill="lightgrey") +
					geom_point(data = locs[longitude>=min.long.na & longitude<= max.long.na][latitude>=min.lat.na & latitude<=max.lat.na], 
								aes(x=longitude, y=latitude, color=set, position="dodge"), size=5) + 
					#geom_jitter(data = locs[jitter==T], aes(x=longitude, y=latitude, color=set, width=4, height=0), size=3) + 		  	
					geom_text(data = locs[longitude>=min.long.na & longitude<= max.long.na][latitude>=min.lat.na & latitude<=max.lat.na], 
								aes(x=longitude, y=latitude, label=nYears), size=3) + 		  	
					xlab("Longitude") + ylab("Latitude")


    #plot_grid(northamerica_tidy, europe_tidy, rel_widths=c(1.35, 1))
		#ggsave(plot_grid(northamerica, europe, rel_widths=c(1.35, 1)), file="~/map.pdf")


    ###############
### ALL MAP ###
###############

	locs <- fread("all_popinfo_formap.csv")
	locs.ag <- locs[,list(latitude=mean(as.numeric(latitude)), longitude=mean(as.numeric(longitude)), n=length(latitude), set="foo"), list(locale)]

	world <- as.data.table(map_data("world"))

	### make maps

		min.lat.eu <- 35
		max.lat.eu <- 55
		min.long.eu <- -10
		max.long.eu <- 37

		europe <- 	ggplot() + 
					geom_polygon(data = world[long>=min.long.eu & long<= max.long.eu][lat>=min.lat.eu & lat<=max.lat.eu], 
								aes(x=long, y = lat, group = group), fill="lightgrey") +
					geom_point(data = locs.ag[longitude>=min.long.eu & longitude<= max.long.eu][latitude>=min.lat.eu & latitude<=max.lat.eu], 
								aes(x=longitude, y=latitude, size=I((n-1)/2 + 4)), alpha=.5) + 
					xlab("Longitude") + ylab("Latitude") + scale_fill_manual(values="black")
		## north america
		min.lat.na <- 25
		max.lat.na <- 50
		min.long.na <- -130
		max.long.na <- -65

		
	
		northamerica <- ggplot() + 
					geom_polygon(data = world[long>=min.long.na & long<= max.long.na][lat>=min.lat.na & lat<=max.lat.na], 
								aes(x=long, y = lat, group = group), fill="lightgrey") +
					geom_point(data = locs.ag[longitude>=min.long.na & longitude<= max.long.na][latitude>=min.lat.na & latitude<=max.lat.na], 
								aes(x=longitude, y=latitude, position="dodge", size=I((n-1)/2 + 4), fill=set), alpha=.5) + 
					xlab("Longitude") + ylab("Latitude") + scale_fill_manual(values="black")
				
    plot_grid(northamerica_tidy+theme_cowplot(), europe_tidy+theme_cowplot(), northamerica+theme_cowplot(), europe+theme_cowplot(), rel_widths=c(1.35, 1))
		#ggsave(plot_grid(northamerica_tidy, europe_tidy, northamerica, europe, rel_widths=c(1.35, 1)), file="~/map_all.pdf", width=10, height=6)
```


## Figure 1C- PCA
```{r}
# object df2
load("../results/df2_objects_PCA_Oct2020_BA_VIswitch.Rdata")

mycol = brewer.pal(n=9, "Spectral")
mycol2 = colorRampPalette(mycol)(13)
mycolEUR = c("#cccccc","#969696","#525252")
mycolCA = c("#9e9ac8","#6a51a3")
mycol3 = c(mycolEUR, mycolCA, mycol2)

#pca_plot_prcomp =
ggplot(data=df2, aes(pc1*(-1), pc2*(-1))) +
  geom_point(aes(pc1*(-1), pc2*(-1), color=pop), size=1.5) +
  scale_color_manual('Location', values = mycol3) +
  #guides(fill=guide_legend(override.aes=list(colour=c(a="green",b="red"))))
  geom_point(aes(fill=pop, shape=Season), size=2) +
  scale_fill_manual('Location', values = mycol3, guide=FALSE) +
  scale_shape_manual('Season', values = c(fall=21,spring=24)) +
  ylab("PC 2") +
  xlab("PC 1") +
  theme_cowplot()+
  theme(#legend.direction="vertical",
    #legend.justification=c("left"),
    #legend.position=c(0.01,0.9),
    legend.key.size = unit(0.35, "cm"),
    legend.background=element_rect(fill="transparent", colour="white", linetype="solid", size=.25),
    legend.text=element_text(size=8),
    legend.title=element_text(size=10),
    legend.title.align=.5,
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 12)),
    axis.text=element_text(size=8),
    axis.title=element_text(size=10) )
#save_plot(pca_plot_prcomp , file="PCA_allsamples_ggplot_prcomp_Oct2020.pdf", base_aspect_ratio = 1.6, base_height=3)
```
